ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ br.com.gabryel.movieclub.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/movieclub"
    url = ${?DATABASE_URL}
    user = "postgres"
    user = ${?DATABASE_USER}
    password = "postgres"
    password = ${?DATABASE_PASSWORD}
}

jwt {
    secret = "dev-secret-do-not-use-in-production"
    secret = ${?JWT_SECRET}
    issuer = "movie-club"
    audience = "movie-club-users"
}

tmdb {
    apiKey = ${?TMDB_API_KEY}
    accessToken = ${?TMDB_ACCESS_TOKEN}
}

omdb {
    apiKey = ${?OMDB_API_KEY}
}

aws {
    accessKeyId = ${?AWS_ACCESS_KEY_ID}
    secretAccessKey = ${?AWS_SECRET_ACCESS_KEY}
    region = ${?AWS_REGION}
    bucketName = ${?S3_BUCKET_NAME}
}
